openapi: "3.1.0"
info:
  title: TrueX Token Risk API
  version: 1.0.0
  description: Evaluates token trust scores based on Birdeye data
servers:
  - url: https://token-risk-api.onrender.com
paths:
  /risk:
    get:
      summary: Get trust score for a token
      operationId: getTokenRisk
      parameters:
        - name: token_address
          in: query
          required: true
          schema:
            type: string
          description: Contract address of the token
      responses:
        "200":
          description: Token risk report
          content:
            application/json:
              schema:
                type: object
                title: TokenRiskResponse
                properties:
                  trust_score:
                    type: number
                    description: The overall trust score (0-100)
                  holder_distribution_score:
                    type: number
                    description: Score for holder concentration
                  info_completeness_score:
                    type: number
                    description: Score for completeness of token info
                  pool_quality_score:
                    type: number
                    description: Score for liquidity pool quality
                  token_age_score:
                    type: number
                    description: Score for token longevity
                  transaction_volume_score:
                    type: number
                    description: Score for trading activity

  /.well-known/openapi.yaml:
    get:
      summary: Serve OpenAPI spec for GPT plugin
      operationId: serveOpenAPI
      responses:
        "200":
          description: OpenAPI YAML file
          content:
            text/yaml:
              schema:
                type: string
                title: OpenAPISpecText